services:

  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"    # RabbitMQ main port (AMQP)
      - "15672:15672"  # RabbitMQ management GUI
